name:                streaming-pcap
version:             1.1.1
synopsis:            Stream packets via libpcap.
description:         Stream packets via libpcap. Requires `libpcap` to be installed.
homepage:            https://github.com/fosskers/streaming-pcap
license:             BSD3
author:              Colin Woodbury
maintainer:          colingw@gmail.com
copyright:           2018 Colin Woodbury
category:            Web

extra-source-files:
  - README.md
  - CHANGELOG.md
  - test/*.pcap

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - attoparsec >= 0.13 && < 0.14
  - bytestring
  - pcap >= 0.4 && < 0.5
  - streaming >= 0.1 && < 0.3
  - streaming-bytestring >= 0.1 && < 0.2
  - streaming-utils >= 0.1 && < 0.2

library:
  source-dirs: .
  other-modules: []

tests:
  streaming-pcap-test:
    main: Test.hs
    source-dirs: test
    other-modules: []
    ghc-options:
      - -threaded
    dependencies:
      - streaming-pcap
      - tasty >= 0.11 && < 1.1
      - tasty-hunit >= 0.9 && < 0.11

benchmarks:
  kanji-bench:
    main: Bench.hs
    source-dirs: bench
    other-modules: []
    ghc-options:
      - -threaded
      - -O2
    dependencies:
      - streaming-pcap
      - criterion >= 1.1 && < 1.5
